### ISSUE TITLE
Can you add support to SVG file?

### ISSUE THREAD

**Issue by Alexnoj** [genesistoxical/drop-icons#2]
convert from SVG to ICO

**Comment by genesistoxical** [comment]
Sure, right now I'm starting to work on it, I'll try to do it quickly. The feature will be available in version 2.1.0 :)

**Comment by genesistoxical** [comment]
Version [2.1.1](https://github.com/genesistoxical/drop-icons/releases/tag/2.1.1) has already been released, which includes the improvement you requested. ✅
